### ISSUE TITLE
Can You Update This?

### ISSUE THREAD

**Issue by ZenMaxe** [Idov31/UdpInspector#1]
Hello it's Not Working in windows 10, it shows only local addresses

**Comment by Idov31** [comment]
Please provide the following details:

- Build number 
- Screenshot
- How did you try to run it and if you had external connections open (what is the result you expected to get)

**Comment by ZenMaxe** [comment]
Build Number is V1.0.

![Uploading bugwithudp.jpg…]()

i want get game servers address with this app ( i want create it to use with my app), but app doesn't show any address (even local) from that pid ( game pid) 
but i saw two lines with this error:
`Failed retrieving WSA protocol info: -1`


can you help me? i need that addresses
(Games Tested: Fortnite, Apex Legends)

**Comment by ZenMaxe** [comment]
Build Number is V1.0.

![bugwithudp](https://user-images.githubusercontent.com/57589298/218864122-a53767a4-cf40-4fac-b350-27a964bc7047.png)


i want get game servers address with this app ( i want create it to use with my app), but app doesn't show any address (even local) from that pid ( game pid)
but i saw two lines with this error:
Failed retrieving WSA protocol info: -1

can you help me? i need that addresses
(Games Tested: Fortnite, Apex Legends)

**Comment by Idov31** [comment]
This project is no longer supported, just forgot to archive it.
